##
# (c) 2022-2024 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: CD Data Workflow Template

on:
  workflow_call:
    secrets:
      token:
          required: true
    outputs:
      environment:
        value: ${{ jobs.data.outputs.environment }}
      isRelease:
        value: ${{ jobs.data.outputs.isRelease }}
      isPreRelease:
        value: ${{ jobs.data.outputs.isPreRelease }}
      targetName:
        value: ${{ jobs.data.outputs.targetName }}
      isEnabled:
        value: ${{ jobs.data.outputs.isEnabled }}
      hasQualifier:
        value: ${{ jobs.data.outputs.hasQualifier }}
      deploymentName:
        value: ${{ jobs.data.outputs.deploymentName }}
      cloud:
        value: ${{ jobs.data.outputs.cloud }}
      cloudType:
        value: ${{ jobs.data.outputs.cloudType }}
      apisEnabled:
        value: ${{ jobs.data.outputs.apisEnabled }}
      isAutomatic:
        value: ${{ jobs.data.outputs.isAutomatic }}
      deliveryPush:
        value: ${{ jobs.data.outputs.deliveryPush }}

jobs:
  data:
    outputs:
      environment: ${{ steps.workspace.outputs.workspace }}
      isRelease: ${{ steps.workspace.outputs.isRelease }}
      isPreRelease: ${{ steps.workspace.outputs.isPreRelease }}
      targetName: ${{ steps.workspace.outputs.targetName }}
      isEnabled: ${{ steps.workspace.outputs.isEnabled }}
      hasQualifier: ${{ steps.workspace.outputs.hasQualifier }}
      deploymentName: ${{ steps.workspace.outputs.deploymentName }}
      cloud: ${{ steps.cloud.outputs.result }}
      cloudType: ${{ steps.cloud_type.outputs.result }}
      apisEnabled: ${{ steps.apis_enabled.outputs.result }}
      isAutomatic: ${{ steps.is_automatic.outputs.result }}
      deliveryPush: ${{ steps.workspace.outputs.deliveryPush }}
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.token }}

      # Get the deployments configuration
      - name: Get the deployments configuration
        id: deploy_conf
        uses: mikefarah/yq@master
        with:
          cmd: yq -o=json -I=0 '.cd.deployments' .github/cloudopsworks-ci.yaml
          
      # Get the cloud entry from .github/cloudopsworks-ci.yaml as plain text
      - name: Get Cloud Entry
        id: cloud
        uses: mikefarah/yq@master
        with:
          cmd: yq e '.cd.cloud' .github/cloudopsworks-ci.yaml | tr '[:lower:]' '[:upper:]'

      # Get the cloud type from .github/cloudopsworks-ci.yaml as plain text
      - name: Get Cloud Type
        id: cloud_type
        uses: mikefarah/yq@master
        with:
          cmd: yq e '.cd.cloud_type' .github/cloudopsworks-ci.yaml

      # Get the apis enabled from .github/cloudopsworks-ci.yaml as plain text
      - name: Get APIs Enabled
        id: apis_enabled
        uses: mikefarah/yq@master
        with:
          cmd: yq e '.cd.apis.enabled // false' .github/cloudopsworks-ci.yaml

      # Get the automatic setting from .github/cloudopsworks-ci.yaml as plain text
      - name: Get Automatic Setting
        id: automatic
        uses: mikefarah/yq@master
        with:
          cmd: yq e '.cd.automatic // false' .github/cloudopsworks-ci.yaml

      # Get default Legacy delivery Push Value
      - name: Legacy Delivery Push Value
        uses: mikefarah/yq@v4.33.3
        id: default_delivery_push
        with:
          cmd: yq e -I=0 '.cd.legacyDeliveryPush' .github/cloudopsworks-ci.yaml

      # Set the appropriate workspace from what is configured from the deploy_conf step
      # Result is stored as JSON with the format found on the cd.deployments section on .github/cloudopsworks-ci.yaml
      - name: Set the appropriate workspace
        id: workspace
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.token }}
          script: |
            const deployments = JSON.parse('${{ steps.deploy_conf.outputs.result }}');
            const branch = '${{ github.ref_name }}';

            var environment = '';
            var isRelease = false;
            var isPreRelease = false;
            var targetName = '';
            var isEnabled = true;
            var hasQualifier = false;
            var deploymentName = '';
            var deliveryPush = ${{ steps.default_delivery_push.outputs.result }};
            if ( deliveryPush == null ) {
              deliveryPush = false;
            }
            if ( branch.startsWith('support') ) {
              const oneMatch = deployments.support.find( ({ match }) => branch.match(new RegExp('support/'+match,'g')) );
              environment = oneMatch.env;
              targetName = oneMatch.targetName;
            } else if ( branch.startsWith('release') ) {
              isPreRelease = true;
              isEnabled = (deployments.test['enabled'] == null ? true : (deployments.test['enabled'] === 'true'));
              environment = deployments.test.env;
              if ( 'targetName' in deployments.test ) {
                targetName = deployments.test.targetName;
              }
              deploymentName = `test/${environment}`;
              if ( 'legacyDeliveryPush' in deployments.test ) {
                deliveryPush = deployments.test.legacyDeliveryPush;
              }
            } else if ( branch === 'develop' ) {
              isEnabled = (deployments.develop['enabled'] == null ? true : (deployments.develop['enabled'] === 'true'));
              environment = deployments.develop.env;
              if ( 'targetName' in deployments.develop ) {
                targetName = deployments.develop.targetName;
              }
              deploymentName = `develop/${environment}`;
              if ( 'legacyDeliveryPush' in deployments.develop ) {
                deliveryPush = deployments.develop.legacyDeliveryPush;
              }
            } else {
              // This semver structure is obtained as per specification https://semver.org/ & https://regex101.com/r/vkijKf/1/
              semver = branch.match(/^v(?<major>0|[1-9]\d*)\.(?<minor>0|[1-9]\d*)\.(?<patch>0|[1-9]\d*)(?:-(?<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?/);
              if ( semver != null ) {
                const pre = semver['groups']['prerelease'];
                const buildmeta = semver['groups']['buildmetadata'];
                // buildmeta format is deploy-XXXX.yyy.zzz
                // the metasuffix should be the deploy- prefix
                if ( pre != null && buildmeta != null) {
                  const metasuffix = buildmeta.match(/deploy-(?<data>.*)/);
                  isEnabled = (deployments.prerelease['enabled'] == null ? true : (deployments.prerelease['enabled'] === 'true'));
                  isPreRelease = true;
                  hasQualifier = true;
                  environment = deployments.prerelease.targets[metasuffix.groups.data].env;
                  if ( 'targetName' in deployments.prerelease.targets[metasuffix.groups.data] ) {
                    targetName = deployments.prerelease.targets[metasuffix.groups.data].targetName;
                  }
                  deploymentName = `prerelease/${buildmeta}/${environment}`;
                  if ( 'legacyDeliveryPush' in deployments.prelease.targets[metasuffix.groups.data] ) {
                    deliveryPush = deployments.prelease.targets[metasuffix.groups.data].legacyDeliveryPush;
                  }
                } else if ( pre != null ) {
                  isEnabled = (deployments.prerelease['enabled'] == null ? true : (deployments.prerelease['enabled'] === 'true'));
                  // Regular expression to match following semver pattern: v1.0.2-alpha.10-uoiretu834u
                  isPreRelease = true;
                  environment = deployments.prerelease.env;
                  if ( 'targetName' in deployments.prerelease ) {
                    targetName = deployments.prerelease.targetName;
                  }
                  deploymentName = `prerelease/${environment}`;
                  if ( 'legacyDeliveryPush' in deployments.prelease ) {
                    deliveryPush = deployments.prelease.legacyDeliveryPush;
                  }
                } else if ( buildmeta != null ) {
                  const metasuffix = buildmeta.match(/deploy-(?<data>.*)/);
                  isRelease = true;
                  hasQualifier = true;
                  environment = deployments.release.targets[metasuffix.groups.data].env;
                  if ( 'targetName' in deployments.release.targets[metasuffix.groups.data] ) {
                    targetName = deployments.release.targets[metasuffix.groups.data].targetName;
                  }
                  deploymentName = `release/${buildmeta}/${environment}`;
                  if ( 'legacyDeliveryPush' in deployments.release.targets[metasuffix.groups.data] ) {
                    deliveryPush = deployments.release.targets[metasuffix.groups.data].legacyDeliveryPush;
                  }
                } else {
                  isRelease = true;
                  environment = deployments.release.env;
                  if ( 'targetName' in deployments.release ) {
                    targetName = deployments.release.targetName;
                  }
                  deploymentName = `release/${environment}`;
                  if ( 'legacyDeliveryPush' in deployments.release ) {
                    deliveryPush = deployments.release.legacyDeliveryPush;
                  }
                }
              } else if ( branch === 'master' || branch === 'main' ) {
                isRelease = true;
                environment = deployments.release.env;
                if ( 'targetName' in deployments.release ) {
                  targetName = deployments.release.targetName;
                }
                deploymentName = `release/${environment}`;
                if ( 'legacyDeliveryPush' in deployments.release ) {
                  deliveryPush = deployments.release.legacyDeliveryPush;
                }
              } else {
                core.setFailed('Branch not supported');
              }
            }
            
            // Check some conditions in order to report back proper variables:
            // DOCKER_REGISTRY
            // BUILD_AWS_REGION
            // BUILD_AWS_STS_ROLE_ARN
            // 
            const targetCloud = '${{ steps.cloud.outputs.result }}';
            // get registry variable from org
            const registry_var = `DOCKER_REGISTRY_${environment}`;
            const {data : registry} = await github.rest.actions.getOrgVariable({
              org: context.repo.owner,
              name: registry_var
            }).then((response) => {
              return response.data;
            }).catch((error) => {
              core.error(`Error getting ${registry_var} from org variables`);
              core.error(error);
              return {};
            });
            
            core.info(`${registry_var} == ${registry}`);
              
            const outputV = { 
              environment: environment, 
              isPreRelease: isPreRelease, 
              isRelease: isRelease,
              targetName: targetName,
              isEnabled: isEnabled,
              hasQualifier: hasQualifier,
              deploymentName: deploymentName,
              deliveryPush: deliveryPush
            }; 
            core.setOutput('workspace', environment);
            core.setOutput('isRelease', isRelease);
            core.setOutput('isPreRelease', isPreRelease);
            core.setOutput('targetName', targetName);
            core.setOutput('isEnabled', isEnabled);
            core.setOutput('hasQualifier', hasQualifier);
            core.setOutput('deploymentName', deploymentName);
            core.setOutput('deliveryPush', deliveryPush);

            return outputV;
