##
# (c) 2023 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: Create Release

on:
  workflow_call:
    inputs:
      release-tag:
        required: true
        type: string
      files-globs:
        required: false
        default: |
            target/*.zip
            target/*.tgz
        type: string
      pre-release:
        required: false
        default: false
        type: boolean
      latest:
        required: false
        default: false
        type: boolean
    secrets:
      token:
        required: true

jobs:
  # Get base version in case of PR merges?
  base-version:
    runs-on: ubuntu-latest
    if: ${{ inputs.pre-release == false }}
    outputs:
      version: ${{ steps.base.outputs.version }}
    steps:
      - name: Checkout target to extract latest tag
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.token }}
          fetch-depth: 1
          ref: ${{ github.base_ref }}

      - name: Base Version get
        id: base
        run: |
          VER=$(make gitflow/version/semver 2>/dev/null)
          echo "version=$VER" >> $GITHUB_OUTPUT

  # Pre release tagging (because not done elsewhere)
  pre-release-tag:
    uses: cloudopsworks/base-app-template/.github/workflows/gitflow-push-tag.yml@develop
    if: ${{ inputs.pre-release == true }}
    secrets:
      token: ${{ secrets.token }}
    with:
      commit_user: ${{ github.actor }}
      commit_email: ${{ github.actor }}@users.noreply.github.com

  # Changelog generation
  changelog:
    if: ${{ always() }}
    needs:
      - base-version
      - pre-release-tag
    runs-on: ubuntu-latest
    outputs:
      contents: ${{ steps.changelog.outputs.changelog }}
    steps:
      - name: Checkout target to extract latest tag
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.token }}
          fetch-depth: 0

      - name: Changelog Generation
        uses: heinrichreimer/action-github-changelog-generator@v2.3
        id: changelog
        with:
          token: ${{ secrets.token }}
          sinceTag: ${{ needs.base-version.outputs.version }}

  ## Actual creation of the release
  create:
    needs:
      - changelog
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: all-artifacts

      - name: Dump Changelog contents
        run: |
          echo "${{ needs.changelog.outputs.contents }}" > CHANGELOG.md
          cat CHANGELOG.md

      - name: Normalize version Tag
        id: normalize
        uses: actions/github-script@v6
        with:
          script: |
            const relTag = '${{ inputs.release-tag }}'
            var release = relTag;
            if ( !relTag.startsWith('v') ) {
              release = 'v' + relTag; 
            }
            return release;

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.token }}
          body_path: CHANGELOG.md
          name: "Release ${{ steps.normalize.outputs.result }}"
          tag_name: ${{ steps.normalize.outputs.result }}
          prerelease: ${{ inputs.pre-release }}
          files: ${{ inputs.files-globs }}
          