##
# (c) 2023 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: Create Release

on:
  workflow_call:
    inputs:
      ref_name:
        required: true
        type: string
      release-tag:
        required: true
        type: string
      files-globs:
        required: false
        default: |
            target/*.zip
            target/*.tgz
        type: string
      pre-release:
        required: false
        default: false
        type: boolean
      latest:
        required: false
        default: false
        type: boolean
    secrets:
      token:
        required: true

jobs:
  # Precondition the release is already tagged
  normalize:
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.normalize.outputs.result }}
    steps:
      - name: Normalize version Tag
        id: normalize
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const relTag = '${{ inputs.release-tag }}'
            var release = relTag;
            if ( !relTag.startsWith('v') ) {
              release = 'v' + relTag; 
            }
            return release;

  # Changelog generation
  changelog:
    needs:
      - normalize
    runs-on: ubuntu-latest
    outputs:
      contents: ${{ steps.changelog.outputs.changelog }}
    steps:
      - name: Checkout target to extract latest tag
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.token }}
          fetch-depth: 0

      - name: Changelog Generation
        uses: requarks/changelog-action@v1
        id: changelog
        with:
          token: ${{ secrets.token }}
          tag: ${{ needs.normalize.outputs.release }}
          writeToFile: false
          includeInvalidCommits: true

  ## Actual creation of the release
  create:
    if: ${{ always() }}
    needs:
      - changelog
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: all-artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.token }}
          body: ${{ needs.changelog.outputs.changes }}
          name: "Release ${{ needs.normalize.outputs.release }}"
          tag_name: ${{ needs.normalize.outputs.release }}
          prerelease: ${{ inputs.pre-release }}
          files: ${{ inputs.files-globs }}
          